import type { Metadata } from "next";
import "./globals.css";
import "./iconglobals.css";

import { Lexend } from "next/font/google";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("RootLayout :>> ", RootLayout);
  return (
    <html lang="en">
      <body className={lexend.className}>{children}</body>
    </html>
  );
}
